env:
  browser: true
extends: "plugin:vue/vue3-recommended"
rules:
  indent: # 缩进2格
    - error
    - 2
  linebreak-style: # LF风格的换行(\n)
    - error
    - unix
  space-before-blocks: # 块前无空格报错
    - error
  no-trailing-spaces: # 结束有空格报错
    - error
  object-curly-spacing: # 对象前后无空格报错
    - error
    - always
  quotes: # 非单引号报错
    - error
    - single
  array-bracket-spacing: # 数组前后有空格报错
    - error
    - never
  max-len: 1 # 限制一行最大长度为80字符
